name: Install NPM packages
description: Install node modules

runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        export HUSKY=0
        export SKIP_INSTALL_SIMPLE_GIT_HOOKS=1

        npm config set audit=false fund=false

        npm ci
