name: Build and publish NPM package

on:
  push:
    branches:
      - main

jobs:
  publish:
    uses: cloudbeds/workflows/.github/workflows/npm-build-test-release.yml@main
    secrets: inherit
    permissions:
      id-token: write
      contents: write
